apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-board
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/OhDongI/CloudNative.git'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cloudnative
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
