apiVersion: v1
kind: Service
metadata:
  name: board-backend
  namespace: cloudnative
spec:
  type: NodePort
  selector:
    app: board-backend
  ports:
    - port: 4000         # 클러스터 내부 포트
      targetPort: 4000   # 컨테이너 포트
      nodePort: 30002    # 호스트(VM)에서 접근하는 포트 (30000~32767 사이)
      