apiVersion: v1
kind: Service
metadata:
  name: board-frontend
  namespace: cloudnative
spec:
  type: NodePort
  selector:
    app: board-frontend
  ports:
    - port: 80          # 클러스터 내부 포트
      targetPort: 80    # 컨테이너 포트
      nodePort: 30001   # 호스트(브라우저에서 접근할 포트)
