apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-frontend
  namespace: cloudnative
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board-frontend
  template:
    metadata:
      labels:
        app: board-frontend
    spec:
      containers:
        - name: frontend
          image: ohdongi/cloudnative-frontend:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80
